"""make_payment_escrow_id_nullable

Revision ID: 6d52183b1cf8
Revises: 98bde08d99a2
Create Date: 2026-07-04 14:44:46.113914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d52183b1cf8'
down_revision: Union[str, Sequence[str], None] = '98bde08d99a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'escrow_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'escrow_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
